apiVersion: v1
kind: Pod
metadata:
  labels:
  name: ngnix-storage
spec:
  containers:
  - image: ngnix
    name: ngnix
    volumeMounts:
      - mountPath: /scratch
        name: scratch-volume
  - image: busybox
    name: busybox
    command: ["/bin/sh","-c"]#run this binary in a nno interactive shell !
    args: ["sleep 1000"]
    volumeMounts:
    - mountPath: /scratch
      name: scratch-volume
  volumes:
  - name: scratch-volume
    persistentVolumeClaim:
      claimName: mealie-data
      

